### ISSUE TITLE
Transcript search-term highlighting not always catching all occurrences of search term in page

### ISSUE THREAD

**Issue by pdeschner** [harvard-lil/nuremberg#13]
E.g., searching on "exhibit," the user is told accurately that 3 occurrences of that term appear on p. 11360 of the Case 1 transcript, but when the user clicks through to p. 11360 only 2 of the 3 occurrences are highlighted, as in the following, where "exhibit" in the snippet "reception of the exhibits in evidence" is not highlighted:

![exhibit_search_highlighting_error](https://cloud.githubusercontent.com/assets/1544067/16329903/988413fa-39b3-11e6-8cb5-d892b4c97399.png)

**Comment by emmalemma** [comment]
This is fixed in 95a2bdaefcf57e8e7299ccc3381aaaf1103b1a29. Be advised that in-transcript highlighting _will_ differ on occasion from what shows up in the search results, since it's done client-side to save CPU and it's not really feasible to reimplement Solr's query parsing or highlighting behavior. But it should be much more thorough now.
