### ISSUE TITLE
Index for transcript links?

### ISSUE THREAD

**Issue by pdeschner** [harvard-lil/nuremberg#15]
Were we still going to look into indexing transcript links, per your suggestion earlier?

**Comment by emmalemma** [comment]
In the sense of references in a transcript page being indexed to that page? That's there, as you can see in a search for say `evidence:NO-080` it says `Evidence Codes Referenced: NO-476, NO-080, NO-227`. (Although for technical reasons, it only lists evidence codes referenced in the pages that are excerpted for the search result. And due to the way highlighting works in Solr, the reference will only be highlighted if the code is also found in the text as well as the index.) 

Perhaps you noticed that evidence and exhibit codes weren't indexed with the generic search terms, such that a search for simply `NO-081` wouldn't return any documents? I've added the codes to the generic search field, so that is now working. Though due to keyword search you'll also see the "Prosecution 81" exhibit, unless you search for the exact phrase `"NO-081"`.

If there's something else you're thinking of you'll have to be more specific.

**Comment by pdeschner** [comment]
That sounds fine.
