### ISSUE TITLE
Transcript search-terms highlighting (in search results, snippets and on transcript page) not working in all cases (esp. or exclusively when nos. form part of the search query

### ISSUE THREAD

**Issue by pdeschner** [harvard-lil/nuremberg#21]
E.g., for the following search "no-080 type:transcripts," only "80" (and not "no-808") is highlighted in the snippets display, and then not at all when the user goes clicks on p. 26 (1st result), "80" in the running text isn't highlighted.

Similarly, when searching on "37, and 45" type:transcripts" only "37" and "45" are highlighted in the snippets, and in the text, "37" and "45" and "and" are highlighted wherever they occur, not only when they are part of the phrase "37, and 45"

Similarly:
![search_highlighting_bug](https://cloud.githubusercontent.com/assets/1544067/16441498/f3ce3874-3d98-11e6-98c7-2242e055e02f.png)

**Comment by emmalemma** [comment]
I pushed some index changes for this with 6bf361ff3b8a5fff6e6a48e3d5f1b336b93c8762. There's a few things going on, and there's a limit to what we can do, just due to how Solr highlighting works.

The index is set up to drop short words like "and" from queries, which is good for returning more search results, but bad when used for highlighting. In 6bf361ff3b8a5fff6e6a48e3d5f1b336b93c8762 I have it highlighting a separate field with less aggressive index settings, so that should be mostly fixed. But the tradeoff is sometimes it won't highlight anything, if it doesn't see the match.

There's also the issue of how "NO-122" is parsed, since it gets tokenized into ["no", "122"] and "no" matches a lot. Nothing to really do about that, but I changed the transcript links to be exact searches like `evidence:"NO-122"`, which should mean you don't run across this as much in practice.

I also fixed the transcript page highlighting to look for quoted phrases, so that should be a bit more accurate as well.
