### ISSUE TITLE
On the search-results page's data slider, update results immediately after date range defined

### ISSUE THREAD

**Issue by pdeschner** [harvard-lil/nuremberg#6]
Currently, the user defines the date range and then must click the arrow in order to execute the filter.  Would it be possible to begin updating as soon as the user has finished defining the date range -- similar to the behavior of the date slider in StackLife: http://stacklife.harvard.edu/search?search_type=keyword&q=finland&submit_search=Go%21

**Comment by emmalemma** [comment]
Thanks for reminding me I meant to implement ajax search results! That's done, and this is done as a side effect.

Unfortunately this specific feature is tricky, since changing the date range can change the visible facets, moving the date slider-- which is extremely surprising. As a compromise, it applies itself a second after you release the slider, giving you a moment to change it again. Go ahead and close this if that seems acceptable.

**Comment by pdeschner** [comment]
A couple issues:
1. The default year range indicated in the date-range slider's year boxes seems not to reflect the range reflected in the facet years: e.g., doc-searching on "brandt" generates facet years from 1936 to 1946, while the date slider's year boundaries indicate 1923 to 1940.  Could this be modified to reflect the actual years?
2. It seems as though the arrow formerly required is no longer necessary?  Also, if the user clicks on it, further modification of the year range seems disabled.

**Comment by emmalemma** [comment]
Good idea, the year range will now be the range of result years unless there is a year range filter applied.

I fixed the range arrow button. The button is still needed to signal that the year input boxes can be edited manually as well. But if you feel it would be cleaner, I can remove it.

**Comment by pdeschner** [comment]
Looks great -- thanks!
